@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Nov 18 18:25:06 +0100 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim mux_16_1_tb_time_impl -key {Post-Implementation:sim_1:Timing:mux_16_1_tb} -tclbatch mux_16_1_tb.tcl -log simulate.log"
call xsim  mux_16_1_tb_time_impl -key {Post-Implementation:sim_1:Timing:mux_16_1_tb} -tclbatch mux_16_1_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
